CREATE INDEX "account_user_idx" ON "accounts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "account_provider_idx" ON "accounts" USING btree ("provider_id","account_id");--> statement-breakpoint
CREATE INDEX "affiliate_user_idx" ON "affiliate_profiles" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "affiliate_status_idx" ON "affiliate_profiles" USING btree ("status");--> statement-breakpoint
CREATE INDEX "categories_parent_idx" ON "categories" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "dispute_order_idx" ON "dispute_tickets" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "dispute_opened_idx" ON "dispute_tickets" USING btree ("opened_by_id");--> statement-breakpoint
CREATE INDEX "mpesa_order_idx" ON "mpesa_transactions" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "mpesa_checkout_idx" ON "mpesa_transactions" USING btree ("checkout_request_id");--> statement-breakpoint
CREATE INDEX "orders_vendor_idx" ON "orders" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "orders_affiliate_idx" ON "orders" USING btree ("affiliate_id");--> statement-breakpoint
CREATE INDEX "orders_product_idx" ON "orders" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "orders_vendor_created_idx" ON "orders" USING btree ("vendor_id","created_at");--> statement-breakpoint
CREATE INDEX "orders_affiliate_created_idx" ON "orders" USING btree ("affiliate_id","created_at");--> statement-breakpoint
CREATE INDEX "orders_status_idx" ON "orders" USING btree ("order_status");--> statement-breakpoint
CREATE INDEX "orders_payment_idx" ON "orders" USING btree ("payment_status");--> statement-breakpoint
CREATE INDEX "payout_user_idx" ON "payout_requests" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "payout_status_idx" ON "payout_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "product_vendor_idx" ON "products" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "products_category_idx" ON "products" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "product_status_idx" ON "products" USING btree ("status");--> statement-breakpoint
CREATE INDEX "product_vendor_status_idx" ON "products" USING btree ("vendor_id","status");--> statement-breakpoint
CREATE INDEX "product_category_status_idx" ON "products" USING btree ("category_id","status");--> statement-breakpoint
CREATE INDEX "reviews_product_idx" ON "reviews" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "reviews_vendor_idx" ON "reviews" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "session_user_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "vendor_user_idx" ON "vendor_profiles" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "vendor_status_idx" ON "vendor_profiles" USING btree ("status");